### ISSUE TITLE
Webstat is non-functional?

### ISSUE THREAD

**Issue by edmcman** [SWI-Prolog/webstat#2]
Thanks for the earlier fix Jan.  Unfortunately, the interface is not loading correctly for me at all.  This is a new machine, but I'm not sure what I could have done to have caused this.  SWI and webstat are both at `master`.

![image](https://user-images.githubusercontent.com/1017189/75718731-7aec0680-5ca1-11ea-8e70-fe7d042b8767.png)

**Comment by JanWielemaker** [comment]
That looks rather odd.  Did you forget to install the JavaScript dependencies?   That said, there are a couple of issues with the current version at various level.   Many things are happening wrt tabling, XSB compatibility and re-thinking some interfaces and this leads to some regression.  I'm investigating the state of webstat and will report if (I think) it works properly again.

**Comment by edmcman** [comment]
Doh I did forget completely about js dependencies.  Sorry!!

**Comment by JanWielemaker** [comment]
That is a relieve :)  Pushed some fixes to both this repo and SWI-Prolog that makes all work fine for me again.   Current SWI-Prolog has proper rational numbers and these could get to the JSON emitting code, resulting in invalid JSON.    Please check and close if all is working as it used to.

**Comment by edmcman** [comment]
Working fine... can't believe I forgot the Javascript assets.  Thanks!
