### ISSUE TITLE
webstat_control: Interval of 60 seconds causes odd behavior

### ISSUE THREAD

**Issue by edmcman** [SWI-Prolog/webstat#3]
If I break a computation and execute ` ws_control(perfchart, [clear,interval(60),start]).`, the resource chart is reset but the sample rate is set to 0.2 seconds.  `interval(61)` works as expected.

**Comment by edmcman** [comment]
Also, if one opens the "Resource usage" tab after having set the interval, the interval is set back to one second.

**Comment by JanWielemaker** [comment]
That should be fixable.  Will try so tomorrow.  Thanks!

**Comment by edmcman** [comment]
Of course.  Sorry it took so long for me to try this :)

By the way, the example in webstat_control should be updated too.

``` prolog
ws_control(perfchart, marking('foo'))
```
 did not work for me.  I had to do: 
``` prolog
ws_control(perfchart, marking([label='foo']))
```

**Comment by JanWielemaker** [comment]
> ```prolog
> ws_control(perfchart, marking([label='foo']))
> ```

The docs state `marking(+Options)` with _"Options is a dict or valid input for dict_create/3"_  That may be a little dense, but I think it is correct.

**Comment by JanWielemaker** [comment]
> Also, if one opens the "Resource usage" tab after having set the interval, the interval is set back to one second.

That is correct.  The actions only control the open resource chart.   It might be a good idea to trap the request and use it to set defaults.

**Comment by JanWielemaker** [comment]
> If I break a computation and execute ` ws_control(perfchart, [clear,interval(60),start]).`, the resource chart is reset but the sample rate is set to 0.2 seconds. `interval(61)` works as expected.

That doesn't reproduce.   What do you mean by _"break a computation"_?

**Comment by edmcman** [comment]
> That doesn't reproduce. What do you mean by _"break a computation"_?

I just meant that I hit Control-C and broke into a prompt while OOAnalyzer was busy processing.

I'm having trouble reproducing the problem today at all though.

**Comment by edmcman** [comment]
> > ```prolog
> > ws_control(perfchart, marking([label='foo']))
> > ```
> 
> The docs state `marking(+Options)` with _"Options is a dict or valid input for dict_create/3"_ That may be a little dense, but I think it is correct.

That is fine.  I am just saying that the example code does not work.

**Comment by JanWielemaker** [comment]
> That is fine. I am just saying that the example code does not work.

Oops.  Thanks.  Pushed a fix.

**Comment by edmcman** [comment]
I'll re-open if I encounter the "60s" bug again.  I am starting to think that this machine may have hardware problems (it crashed overnight).
